<html>
  <head>
    <title>09.Promises</title>
  </head>
  <body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser-polyfill.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.js"></script>
    <script type="text/babel">

      var p0 = new Promise((resolve, reject) => {  
        if (true)  
          reject("rejected!"); // same as rejection
        else
          resolve(4);
      });

      p0.then((val) => val + 2)  
       .then((val) => console.log("got", val))
       .catch((err) => console.log("error: ", err));



      var p1 = new Promise((resolve, reject) => {  
        if (true)  
          throw new Error("rejected!"); // same as rejection
        else
          resolve(4);
      });


      p1.then((val) => val + 2)  
       .then((val) => console.log("got", val))
       .catch((err) => console.log("error: ", err.message));



      var p2 = new Promise((resolve, reject) => {  
        resolve(4);
      });

      // Second .then throws error, .catch() still handles it
      // as rejection anywhere in the processing chain of promise
      p2.then((val) => val + 2)  
       .then((val) => { throw new Error("step 2 failed!") }) 
       .then((val) => console.log("got", val))
       .catch((err) => console.log("error: ", err.message));
      // => error: step 2 failed!


    </script>
  </body>
</html>

